config/routes.rb
Rails.application.routes.draw do
  get 'calculations/soberanos'
  get 'calculations/fuertes'

  root 'calculations#index'
end

app/models/calculation.rb
class Calculation
  include ActiveModel::Model

  def self.soberanos(value=nil)
    value / 100000 unless value.nil?
  end
  def self.fuertes(value=nil)
    value * 100000 unless value.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  def index
  end

  def soberanos
    value = params[:soberanos][:value] if params[:soberanos].present?
    @result = Calculation.soberanos(value.to_f) if value.present?
  end

  def fuertes
    value = params[:fuertes][:value] if params[:fuertes].present?
    @result = Calculation.fuertes(value.to_f) if value.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/views/calculations/fuertes.html.erb
<div class="jumbotron">  
  <%= simple_form_for :fuertes, method: :get do |f| %>
    <%= f.input :value, label: "Por favor, ingresa el monto en Bolívares 'Soberanos'" %>
    <%= f.submit "Calcular"  %>
  <% end %>

  <% unless @result.nil? %>
    <p>El resultado en Bolívares 'Fuertes' es:</p>
    <h1><%= number_to_currency(@result, unit: "BsF") %></h1>
  <% end %>
</div>
<%= link_to 'Inicio', root_path, class: "btn btn-primary" %>

app/views/calculations/index.html.erb
<h1>Convertir a:</h1>
<p><%= link_to "Bolívares 'Soberanos'", calculations_soberanos_path, class: "btn btn-primary" %></p>
<p><%= link_to "Bolívares 'Fuertes'", calculations_fuertes_path, class: "btn btn-primary" %></p>

app/views/calculations/soberanos.html.erb
<div class="jumbotron">  
  <%= simple_form_for :soberanos, method: :get do |f| %>
    <%= f.input :value, label: "Por favor, ingresa el monto en Bolívares 'Fuertes'" %>
    <%= f.submit "Calcular"  %>
  <% end %>

  <% unless @result.nil? %>
    <p>El resultado en Bolívares 'Soberanos' es:</p>
    <h1><%= number_to_currency(@result, unit: "BsS") %></h1>
  <% end %>
</div>
<%= link_to 'Inicio', root_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculadora</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>